#!/usr/bin/env python3
"""
ME/CE/AM 295 AI TA — Slack bot (Socket Mode).

Two grounded surfaces over the same week-gated RAG backend:

  1. Per-week channels — @ai-ta in #week-NN answers scoped to Week NN.
  2. Agents & AI Apps assistant pane (Slack Developer Program / paid workspace) —
     a dedicated assistant thread with a live status and week-aware suggested
     prompts. Opening the pane from #week-NN auto-scopes it to that week via
     get_thread_context().

Every answer is grounded via pipeline.query.get_context (week-gated + access-
controlled) and generated by Claude.

Run:
    cp .env.example .env   # SLACK_BOT_TOKEN, SLACK_APP_TOKEN, ANTHROPIC_API_KEY, VOYAGE_API_KEY, DATABASE_URL
    python -m bot.app
"""
from __future__ import annotations

import os
import re
import time
from collections import defaultdict

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from pipeline import config as C
from bot.agent import run_agent

WEEK_CHAN_RE = re.compile(r"week-(\d+)", re.I)

# naive per-user rate limit: max 5 requests / 60s
_hits: dict[str, list[float]] = defaultdict(list)
RATE_N, RATE_WINDOW = 5, 60.0


def rate_limited(user: str) -> bool:
    now = time.time()
    hits = [t for t in _hits[user] if now - t < RATE_WINDOW]
    hits.append(now)
    _hits[user] = hits
    return len(hits) > RATE_N


# ------------------------------------------------------------------
# Week resolution
# ------------------------------------------------------------------
def week_from_channel_id(client, channel_id: str | None) -> int | None:
    if not channel_id:
        return None
    try:
        name = client.conversations_info(channel=channel_id)["channel"].get("name", "")
    except Exception:
        return None
    m = WEEK_CHAN_RE.search(name)
    return int(m.group(1)) if m else None


def effective_week(chan_week: int | None) -> tuple[int, str, str | None]:
    """Return (week_to_query, agent, defer_message_or_None)."""
    teaching = C.current_week()
    if chan_week is None:
        return teaching, "all_student_agents", None
    if chan_week > teaching:
        start = dict(C.WEEK_STARTS).get(chan_week)
        when = f" (opens {start:%b %-d})" if start else ""
        return teaching, "concept_tutor", (
            f"Week {chan_week} materials aren't open yet{when}. "
            f"We're currently in Week {teaching}.")
    return chan_week, "concept_tutor", None


def generate_answer(question: str, chan_week: int | None) -> str:
    """Run the week-scoped Claude Agent SDK agent (RAG-as-tool)."""
    week, agent, defer = effective_week(chan_week)
    if defer:
        return defer
    return run_agent(question, week=week, scope="week", agent_name=agent)


def suggested_prompts(week: int) -> list[dict]:
    title = C.WEEK_TITLES.get(week, "this week")
    return [
        {"title": f"Explain a key idea from Week {week}",
         "message": f"Explain a key concept from Week {week} ({title}) simply."},
        {"title": "What should I read this week?",
         "message": f"What are the readings and key papers for Week {week}?"},
        {"title": f"Quiz me on Week {week}",
         "message": f"Ask me a practice question about Week {week} concepts."},
    ]


# ------------------------------------------------------------------
# App
# ------------------------------------------------------------------
def build_app():
    from slack_bolt import App, Assistant

    app = App(token=os.getenv("SLACK_BOT_TOKEN"))
    assistant = Assistant()

    # ---- Agents & AI Apps: the assistant pane ----
    @assistant.thread_started
    def on_thread_started(say, set_suggested_prompts, set_title, get_thread_context, client):
        ctx = get_thread_context()
        week = week_from_channel_id(client, getattr(ctx, "channel_id", None)) or C.current_week()
        say(f"Hi! I'm your ME/CE/AM 295 AI TA, focused on *Week {week} — "
            f"{C.WEEK_TITLES.get(week, '')}*. Ask me anything about the course materials.")
        set_title(f"Week {week} — AI TA")
        set_suggested_prompts(prompts=suggested_prompts(week))

    @assistant.thread_context_changed
    def on_context_changed(set_suggested_prompts, get_thread_context, client):
        ctx = get_thread_context()
        week = week_from_channel_id(client, getattr(ctx, "channel_id", None)) or C.current_week()
        set_suggested_prompts(prompts=suggested_prompts(week))

    @assistant.user_message
    def on_user_message(payload, set_status, say, get_thread_context, client):
        user = payload.get("user")
        text = (payload.get("text") or "").strip()
        if not text:
            return
        if user and rate_limited(user):
            say("You're going a bit fast — give me a moment between questions 🙏")
            return
        ctx = get_thread_context()
        chan_week = week_from_channel_id(client, getattr(ctx, "channel_id", None))
        wk, _, _ = effective_week(chan_week)
        set_status(f"consulting Week {wk} materials…")
        try:
            say(generate_answer(text, chan_week))
        except Exception as e:
            say(f"Sorry — I hit an error reaching my knowledge base ({type(e).__name__}). "
                f"A human TA has been notified.")

    app.use(assistant)

    # ---- Per-week channels: @ai-ta mention ----
    @app.event("app_mention")
    def on_mention(event, say, client):
        user = event.get("user")
        text = re.sub(r"<@[^>]+>", "", event.get("text", "")).strip()
        if not text or not user:
            return
        thread = event.get("thread_ts") or event.get("ts")
        if rate_limited(user):
            say(text="You're going a bit fast — give me a minute between questions 🙏",
                thread_ts=thread)
            return
        chan_week = week_from_channel_id(client, event.get("channel"))
        try:
            reply = generate_answer(text, chan_week)
        except Exception as e:
            reply = (f"Sorry — I hit an error reaching my knowledge base ({type(e).__name__}). "
                     f"A human TA has been notified.")
        say(text=reply, thread_ts=thread)

    @app.event("reaction_added")
    def on_reaction(event, logger):
        if event.get("reaction") in ("star", "star2", "white_check_mark"):
            logger.info(f"positive feedback from {event.get('user')} on {event.get('item')}")
        elif event.get("reaction") in ("triangular_flag_on_post", "rotating_light", "x"):
            logger.info(f"FLAG from {event.get('user')} on {event.get('item')} — human review needed")

    return app


def main():
    from slack_bolt.adapter.socket_mode import SocketModeHandler
    # Optional one-shot channel provisioning at startup (idempotent). Handy with
    # `slack run`, where the CLI injects the bot token into this process.
    if os.getenv("PROVISION_ON_START"):
        try:
            from bot.provision_channels import provision
            print("Provisioning channels…")
            provision()
        except Exception as e:
            print(f"[warn] channel provisioning skipped: {e}")
    app = build_app()
    print("AI TA bot connecting (Socket Mode)…")
    SocketModeHandler(app, os.getenv("SLACK_APP_TOKEN")).start()


if __name__ == "__main__":
    main()
